### ISSUE TITLE
Throttle in Get-AdobeUsers function not working

### ISSUE THREAD

**Issue by robinherbert** [zincarla/AdobeUMInterface#15] opened 2020-01-08 11:19 UTC
@zincarla the throttle code in the Get-AdobeUsers function doesn't work, because the values it's looking for never exist. I've implemented my own code, which seems to work. So submitted it via a Pull request.
I hope this is the right way, since this is my first contribution to Git!
BTW: been using your module for several months now with no issues, until Monday morning when I ran into the throttle issue. I guess Adobe changed something! In my case, pulling back c.4800 users, which seems to need about 24 page requests to complete. Now throttles every 6 page requests. So if you have less than 1200 users to pull back, you may never hit the issue.

**Comment by zincarla** [comment] 2020-01-09 03:28
Thanks for the patch! I merged it in. I did try forcing the throttle to happen, but I was not able to. We do have less than 1200 users though. As for contributing to Git, each repository has it's own rules or requirements. The bigger ones usually publish a document on it. I don't have any official rules. Personally, as long as the issue is explained and the pull request makes sense, I'll probably accept it. Thanks again!

**Closed as completed by zincarla** 2020-01-09 03:28 UTC
